### ISSUE TITLE
Fails building on OS X Maverics and newer

### ISSUE THREAD

**Issue by DarkDimius** [kaitai-io/kaitai_struct_cpp_stl_runtime#10]
```
Scanning dependencies of target kaitai_struct_cpp_stl_runtime
[ 50%] Building CXX object CMakeFiles/kaitai_struct_cpp_stl_runtime.dir/kaitai/kaitaistream.cpp.o
/Users/dark/workspace/tasty/kaitai_struct_cpp_stl_runtime/kaitai/kaitaistream.cpp:3:10: fatal error: 'endian.h' file not found
#include <endian.h>
         ^
1 error generated.
make[2]: *** [CMakeFiles/kaitai_struct_cpp_stl_runtime.dir/kaitai/kaitaistream.cpp.o] Error 1
make[1]: *** [CMakeFiles/kaitai_struct_cpp_stl_runtime.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by DarkDimius** [comment]
Also Tested on El Capitan.

**Comment by GreyCat** [comment]
We totally need CI that would test all popular compilers and OS targets ;)
I bet there are quite a few obstacles on Windows as well, for example...

Unfortunately, I don't have working OS X installation right now, so I can't do anything to this myself. May be this one would be relevant: http://stackoverflow.com/questions/20813028/endian-h-not-found-on-mac-osx

Patches are welcome :)

**Comment by GreyCat** [comment]
Solved in https://github.com/kaitai-io/kaitai_struct_cpp_stl_runtime/pull/14. Travis OS X CI jobs shows that it builds and starts properly, but then it fails on https://travis-ci.org/kaitai-io/ci_targets/jobs/275427867#L459:

```
[100%] Linking CXX executable ks_tests
[100%] Built target ks_tests
Test setup error: boost::runtime::access_to_missing_argument: There is no argument provided for parameter color_output
```

Need to investigate that CI stuff further...

**Comment by GreyCat** [comment]
C++98 builds now pass (99.3%) on OS X: http://kaitai.io/ci/ci.html => cpp_stl_98 clang7.3_osx
C++11 builds are so-so (34.2%) on OS X: http://kaitai.io/ci/ci.html => cpp_stl_11 clang7.3_osx

Given that C++11 is a separate task, I guess we can close this one.
