### ISSUE TITLE
Support for Windows/MSVC

### ISSUE THREAD

**Issue by AlexAltea** [kaitai-io/kaitai_struct_cpp_stl_runtime#11]
Running CMake on Windows results in:

```bash
$ cmake -G "Visual Studio 15 2017" .
CMake Error at CMakeLists.txt:17 (install):
  install Library TARGETS given no DESTINATION!
```

Additionally, there's few issues that arise once you attempt to generate a project manually. These two headers included in `kaitaistream.cpp` are not present in MSVC (see also issue #10).

```cpp
#include <endian.h>
#include <byteswap.h>
```

**Comment by GreyCat** [comment]
My only concern here would be that it was not supposed to be built as a shared library in the first place ;)

**Comment by GreyCat** [comment]
Supposedly solved in https://github.com/kaitai-io/kaitai_struct_cpp_stl_runtime/pull/16. Feel free to reopen if any issues arise.
