### ISSUE TITLE
Modern C++ support

### ISSUE THREAD

**Issue by berkus** [kaitai-io/kaitai_struct_cpp_stl_runtime#13]
Hi!

Is there any plan to support c++14 and/or c++17?

Probably as cpp14_stl and cpp17_stl runtimes?

C++ supports optionals and other useful things now.

**Comment by GreyCat** [comment]
> Is there any plan to support c++14 and/or c++17?

Sure there is: https://github.com/kaitai-io/kaitai_struct/issues/211

> Probably as cpp14_stl and cpp17_stl runtimes?

Unfortunately, it's a somewhat harder task that just changing the runtime. Compiler would need radical changes too.

> C++ supports optionals and other useful things now.

If you mean [std::optional](http://en.cppreference.com/w/cpp/utility/optional), then it's a new feature of C++17, which is not final yet, so probably we should wait at least until the official publication.

**Comment by berkus** [comment]
Eeexcellent, same as rust - I could help if needed. Current generated cpp is fine, but shared_ptr/unique_ptr and optional could be nice additions.

**Comment by GreyCat** [comment]
You're more than welcome to contribute in discussion in https://github.com/kaitai-io/kaitai_struct/issues/211. Basically, what I need is a solid example of how generated C++ code should look like, or explanation of changes that should be done to current C++ generator to achieve C++11/14/17/whatever compatibility.

Also, it looks like that API would change, so help with porting C++ specs to newer standard would be appreciated as well (manually or auto with some sort of a translator script).
