### ISSUE TITLE
how does read_s1() actually work?

### ISSUE THREAD

**Issue by arekbulski** [kaitai-io/kaitai_struct_cpp_stl_runtime#19]
Could someone please explain to me, how does this method actually manage to return anything? The get() does not take a pointer to a variable, it takes a value variable, which means that value gets copied in, but not copied out. How does t contain anything but random garbage?
```cpp
int8_t kaitai::kstream::read_s1() {
    char t;
    m_io->get(t);
    return t;
}
```

**Comment by GreyCat** [comment]
get form 2, [as described here](http://en.cppreference.com/w/cpp/io/basic_istream/get), sets `t` to byte that we've just read. It takes a reference to variable, not a pointer.

**Comment by arekbulski** [comment]
A reference, not pointer. Got it.
