### ISSUE TITLE
snprintf not cross-platform compilable

### ISSUE THREAD

**Issue by tangoalx** [kaitai-io/kaitai_struct_cpp_stl_runtime#28]
The following call leads to an compilation error with Microsoft Visual Studio 2010 VCC, because the function `snprintf` is not known:
https://github.com/kaitai-io/kaitai_struct_cpp_stl_runtime/blob/da224cbd712222043fb9175f6c73ba288b76f2fb/kaitai/kaitaistream.cpp#L541

The function is called `_snprintf` on windows system (just prepend underscore). However, `_snprintf` is deprecated and I'm not sure, if it has already been removed from newer versions of MSVS. Furthermore `snprintf` and `_snprintf` do not behave the same way in all situations (see example on [stack-overflow-thread](https://stackoverflow.com/a/21929706/8225336) or tests on various platforms on [demin-blog](http://demin.ws/blog/english/2013/01/28/use-snprintf-on-different-platforms/))

Maybe there is an alternative solution, which works cross-platform, but I didn't find a cross-platform implementation yet (other than implementing the function anew).

**Comment by GreyCat** [comment]
Probably we can get away by outputting this to in-memory string stream and then returning its contents?
