### ISSUE TITLE
kaitai/exceptions.h is not installed

### ISSUE THREAD

**Issue by volo-zyko** [kaitai-io/kaitai_struct_cpp_stl_runtime#38]
https://github.com/kaitai-io/kaitai_struct_cpp_stl_runtime/blob/4da1668426bd67aaf1932628c1c7db76ff77665c/CMakeLists.txt#L30

`kaitai/exceptions.h` is missing in `PUBLIC_HEADER` which is now required in generated code.

**Comment by digitalTrilunaire** [comment]
I had the same problem, with make install, exceptions.h is not isntalled in /usr/local/include/kaitai
