### ISSUE TITLE
Codestyle in C++

### ISSUE THREAD

**Issue by ghost** [kaitai-io/kaitai_struct_cpp_stl_runtime#4]
Hello guys! You do a great job and generated files work perfect, but anyway I'd like .h files to look more neat. Now private and public fields are mixed together and definitions of nested classes are written right inside of the container classes definitions. It's rather hard to read, especially if there is more than one level of nested structures. I'd like to have a better codestyle:)

It'd also be awesome to see comments in doxygen in .cpp files so that they are documented.

**Comment by GreyCat** [comment]
> I'd like to have a better codestyle:)

Could you provide an example on what you'd like to get? I.e. ordering, number of sections, etc.

> It'd also be awesome to see comments in doxygen in .cpp files so that they are documented.

Um, as far as I understand, Doxygen never uses .cpp files for documentation — that's what .h files are for. Why do you need Doxygen comments in .cpp?

**Comment by DarkDimius** [comment]
As an idea: check if there's an installed clang-format and if there's one invoke it.

**Comment by GreyCat** [comment]
You mean, invoke it to postprocess output from ksc?

**Comment by DarkDimius** [comment]
@GreyCat, precisely.

**Comment by GreyCat** [comment]
Compiler issue, not a runtime issue, and there's indeed already an issue for this in main project: https://github.com/kaitai-io/kaitai_struct/issues/252

Closing this one, please continue discussion there.
