### ISSUE TITLE
`target_include_directories(${PROJECT_NAME} PUBLIC "${CMAKE_CURRENT_SOURCE_DIR}")` is missing from `CMakeLists.txt`

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct_cpp_stl_runtime#53]
Since the generated headers contain includes in the form `#include "kaitai/kaitaistruct.h"`

**Comment by LHLaurini** [comment]
Fixed by #37

**Comment by generalmimon** [comment]
@LHLaurini Thanks, I'm closing this issue as resolved then.
