### ISSUE TITLE
Remove std::invalid_argument dynamic allocation

### ISSUE THREAD

**Issue by m0rl** [kaitai-io/kaitai_struct_cpp_stl_runtime#6]
Two functions seems to be forgotten in this 5a77b30c3 fix,
they are ```kaitai::kstream::mod``` and ```kaitai::kstream::to_string```.

The basic explanation about why we should better not throw dynamically
allocated objects can be found on [stackoverflow](http://stackoverflow.com/questions/10948316/throw-new-stdexception-vs-throw-stdexception). 

> Throwing a pointer to a dynamically allocated object is never a good idea

**Comment by GreyCat** [comment]
Thanks! Seems to be fixed now.
