### ISSUE TITLE
Pre C++11 to_string implementation

### ISSUE THREAD

**Issue by m0rl** [kaitai-io/kaitai_struct_cpp_stl_runtime#8]
I wonder if current ```kaitai::kstream::to_string``` implementation
can be replaced with simple

```c++
std::string kaitai::kstream::to_string(int val) {
  std::stringstream ss;
  ss << val;
  return ss.str();
}
```

Are there any reasons for it to be implemented the way it is now?

**Comment by GreyCat** [comment]
stringstream with construction is usually roughly 8-10x slower than printf solution: http://www.boost.org/doc/libs/1_49_0/doc/html/boost_lexical_cast/performance.html

**Comment by GreyCat** [comment]
More benchmarking: http://zverovich.net/2013/09/07/integer-to-string-conversion-in-cplusplus.html
Actually, even C++11 `std::to_string()` is visibly slower than sprintf :(

**Comment by m0rl** [comment]
Well, according to the second link ```sprintf``` isn't that so fast :)

Anyway, we still can improve current version by removing explicit
return variable construction

```c++
std::string kaitai::kstream::to_string(int val) {
    // if int is 32 bits, "-2147483648" is longest string representation
    //   => 11 chars + zero => 12 chars
    // if int is 64 bits, "-9223372036854775808" is longest
    //   => 20 chars + zero => 21 chars
    char buf[25];
    int got_len = snprintf(buf, sizeof(buf), "%d", val);

    // should never happen, but check nonetheless
    if (got_len > sizeof(buf))
        throw std::invalid_argument("integer is longer than string buffer");

    return std::string(buf);
}
```

Now it is subject for [RVO](https://en.wikipedia.org/wiki/Return_value_optimization)

**Comment by GreyCat** [comment]
Cool, thanks! Just applied your fix. Please check it, and if everything's file, close this issue.

**Comment by m0rl** [comment]
Great! Thanks for an interesting project.
